// بنك أسئلة لغة المرجع - Al-Marjaa Language Questions Bank
// جميع الأسئلة باللغة العربية مع تصنيفات متقدمة

export interface Question {
  id: string;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard' | 'expert';
  category: string;
  points: number;
}

// ============================================
// أسئلة المستوى المبتدئ - Beginner Questions (50+ سؤال)
// ============================================

export const beginnerQuestions: Question[] = [
  // === الصيغة الأساسية ===
  {
    id: 'b1',
    question: 'ما هي الكلمة المفتاحية الصحيحة لتعريف متغير في لغة المرجع؟',
    options: ['متغير', 'var', 'let', 'define'],
    correctAnswer: 0,
    explanation: 'في لغة المرجع، نستخدم الكلمة المفتاحية العربية "متغير" لتعريف المتغيرات، مثال: متغير العدد = 10؛',
    difficulty: 'easy',
    category: 'الصيغة الأساسية',
    points: 1,
  },
  {
    id: 'b2',
    question: 'ما هي الكلمة المفتاحية لتعريف ثابت (قيمة لا تتغير)؟',
    options: ['ثابت', 'const', 'final', 'ثابت_قيمة'],
    correctAnswer: 0,
    explanation: 'نستخدم "ثابت" لتعريف القيم الثابتة، مثال: ثابت باي = 3.14159؛',
    difficulty: 'easy',
    category: 'الصيغة الأساسية',
    points: 1,
  },
  {
    id: 'b3',
    question: 'ما الرمز المستخدم لإنهاء التعليمة في لغة المرجع؟',
    options: ['؛', ';', '.', '،'],
    correctAnswer: 0,
    explanation: 'لغة المرجع تستخدم الفاصلة المنقوطة العربية "؛" لإنهاء التعليمات.',
    difficulty: 'easy',
    category: 'الصيغة الأساسية',
    points: 1,
  },
  {
    id: 'b4',
    question: 'كيف تُطبع رسالة "مرحباً" في لغة المرجع؟',
    options: ['اطبع("مرحباً")؛', 'print("مرحباً")؛', 'cout << "مرحباً"؛', 'console.log("مرحباً")؛'],
    correctAnswer: 0,
    explanation: 'الدالة "اطبع" هي الدالة الأساسية للطباعة في لغة المرجع.',
    difficulty: 'easy',
    category: 'الإدخال والإخراج',
    points: 1,
  },
  {
    id: 'b5',
    question: 'ما هو الناتج: متغير س = 5 + 3؛ اطبع(س)؛؟',
    options: ['8', '53', 'خطأ', '5 + 3'],
    correctAnswer: 0,
    explanation: 'العملية الحسابية 5 + 3 = 8 يتم تخزينها في المتغير س ثم طباعتها.',
    difficulty: 'easy',
    category: 'العمليات الحسابية',
    points: 1,
  },
  // === أنواع البيانات ===
  {
    id: 'b6',
    question: 'ما نوع القيمة "مرحباً بالعالم"؟',
    options: ['نص', 'عدد', 'منطقي', 'قائمة'],
    correctAnswer: 0,
    explanation: 'القيم النصية (strings) في لغة المرجع تُسمى "نص" وتُكتب بين علامتي تنصيص.',
    difficulty: 'easy',
    category: 'أنواع البيانات',
    points: 1,
  },
  {
    id: 'b7',
    question: 'ما نوع القيمة 3.14159؟',
    options: ['عدد_عشري', 'عدد_صحيح', 'نص', 'منطقي'],
    correctAnswer: 0,
    explanation: 'الأعداد العشرية (float) في لغة المرجع تُسمى "عدد_عشري".',
    difficulty: 'easy',
    category: 'أنواع البيانات',
    points: 1,
  },
  {
    id: 'b8',
    question: 'ما القيم الممكنة للنوع "منطقي"؟',
    options: ['صحيح وخطأ', '0 و 1', 'نعم ولا', 'true و false'],
    correctAnswer: 0,
    explanation: 'النوع المنطقي (boolean) يقبل القيمتين "صحيح" و "خطأ" بالعربية.',
    difficulty: 'easy',
    category: 'أنواع البيانات',
    points: 1,
  },
  {
    id: 'b9',
    question: 'ما نوع القيمة 42؟',
    options: ['عدد_صحيح', 'عدد_عشري', 'نص', 'منطقي'],
    correctAnswer: 0,
    explanation: 'الأعداد الصحيحة بدون فاصلة عشرية هي من النوع "عدد_صحيح".',
    difficulty: 'easy',
    category: 'أنواع البيانات',
    points: 1,
  },
  {
    id: 'b10',
    question: 'كيف تُعرّف متغيراً من نوع نص؟',
    options: ['متغير الاسم: نص = "أحمد"؛', 'var name: string = "Ahmed"', 'متغير الاسم = "أحمد"؛', 'string name = "Ahmed"'],
    correctAnswer: 0,
    explanation: 'يمكن تحديد نوع المتغير صراحة باستخدام النقطتين بعد اسم المتغير.',
    difficulty: 'medium',
    category: 'أنواع البيانات',
    points: 2,
  },
  // === العمليات الحسابية ===
  {
    id: 'b11',
    question: 'ما نتيجة: 10 % 3؟',
    options: ['1', '3', '0', '10'],
    correctAnswer: 0,
    explanation: 'عملية % (باقي القسمة) ترجع باقي قسمة 10 على 3 وهو 1.',
    difficulty: 'easy',
    category: 'العمليات الحسابية',
    points: 1,
  },
  {
    id: 'b12',
    question: 'ما العملية المستخدمة للأس؟ مثال: 2³',
    options: ['**', '^', 'أس', 'pow'],
    correctAnswer: 0,
    explanation: 'لغة المرجع تستخدم ** للأس، مثال: 2 ** 3 = 8.',
    difficulty: 'easy',
    category: 'العمليات الحسابية',
    points: 1,
  },
  {
    id: 'b13',
    question: 'ما نتيجة: 15 // 4؟',
    options: ['3', '4', '3.75', 'خطأ'],
    correctAnswer: 0,
    explanation: 'القسمة الصحيحة // ترجع الناتج الصحيح فقط (بدون الكسر).',
    difficulty: 'medium',
    category: 'العمليات الحسابية',
    points: 2,
  },
  {
    id: 'b14',
    question: 'ما نتيجة: 2 ** 4؟',
    options: ['16', '8', '4', '6'],
    correctAnswer: 0,
    explanation: '2 أس 4 = 2 × 2 × 2 × 2 = 16.',
    difficulty: 'easy',
    category: 'العمليات الحسابية',
    points: 1,
  },
  {
    id: 'b15',
    question: 'ما أولوية العمليات في: 2 + 3 * 4؟',
    options: ['14', '20', '9', '24'],
    correctAnswer: 0,
    explanation: 'الضرب له أولوية على الجمع، لذا 3 * 4 = 12، ثم 2 + 12 = 14.',
    difficulty: 'easy',
    category: 'العمليات الحسابية',
    points: 1,
  },
  // === التعليقات ===
  {
    id: 'b16',
    question: 'كيف تكتب تعليق سطر واحد في لغة المرجع؟',
    options: ['// تعليق', '# تعليق', '-- تعليق', '/* تعليق */'],
    correctAnswer: 0,
    explanation: 'التعليقات السطرية تبدأ بـ // مثل العديد من اللغات الحديثة.',
    difficulty: 'easy',
    category: 'التعليقات',
    points: 1,
  },
  {
    id: 'b17',
    question: 'كيف تكتب تعليقاً متعدد الأسطر؟',
    options: ['/* تعليق\n متعدد */', '// تعليق //', '# تعليق #', '<!-- تعليق -->'],
    correctAnswer: 0,
    explanation: 'التعليقات المتعددة الأسطر تُكتب بين /* و */.',
    difficulty: 'easy',
    category: 'التعليقات',
    points: 1,
  },
  // === المقارنة ===
  {
    id: 'b18',
    question: 'ما رمز "يساوي" للمقارنة بين قيمتين؟',
    options: ['==', '=', '===', 'يساوي'],
    correctAnswer: 0,
    explanation: 'نستخدم == للمقارنة و = للإسناد، مثل اللغات الأخرى.',
    difficulty: 'easy',
    category: 'عمليات المقارنة',
    points: 1,
  },
  {
    id: 'b19',
    question: 'ما رمز "لا يساوي"؟',
    options: ['!=', '<>', '=/=', '≠'],
    correctAnswer: 0,
    explanation: 'نستخدم != للتحقق من عدم المساواة.',
    difficulty: 'easy',
    category: 'عمليات المقارنة',
    points: 1,
  },
  {
    id: 'b20',
    question: 'ما نتيجة: 5 >= 5؟',
    options: ['صحيح', 'خطأ', '5', 'خطأ في الصيغة'],
    correctAnswer: 0,
    explanation: '>=(أكبر أو يساوي) تُرجع صحيح لأن 5 يساوي 5.',
    difficulty: 'easy',
    category: 'عمليات المقارنة',
    points: 1,
  },
  // === المصفوفات ===
  {
    id: 'b21',
    question: 'كيف تُعرّف مصفوفة فارغة؟',
    options: ['[]', '{}', '()', '<>'],
    correctAnswer: 0,
    explanation: 'المصفوفات تُعرّف بأقواس مربعة [].',
    difficulty: 'easy',
    category: 'المصفوفات',
    points: 1,
  },
  {
    id: 'b22',
    question: 'ما هي نتيجة: "مرحباً" + " " + "عالم"؟',
    options: ['مرحباً عالم', 'مرحباًعالم', 'خطأ', 'مرحباً  عالم'],
    correctAnswer: 0,
    explanation: 'العملية + مع النصوص تقوم بالدمج (concatenation).',
    difficulty: 'easy',
    category: 'النصوص',
    points: 1,
  },
  {
    id: 'b23',
    question: 'كيف تصل للعنصر الثاني في مصفوفة [10, 20, 30]؟',
    options: ['المصفوفة[1]', 'المصفوفة[2]', 'المصفوفة.ثاني', 'ثاني(المصفوفة)'],
    correctAnswer: 0,
    explanation: 'الفهرسة تبدأ من 0، فالعنصر الثاني يكون في الفهرس 1.',
    difficulty: 'easy',
    category: 'المصفوفات',
    points: 1,
  },
  {
    id: 'b24',
    question: 'كيف تُعرّف مصفوفة بأرقام؟',
    options: ['[1، 2، 3]', '{1, 2, 3}', '(1, 2, 3)', '[1; 2; 3]'],
    correctAnswer: 0,
    explanation: 'المصفوفات تُعرّف بأقواس مربعة والفاصلة العربية "،".',
    difficulty: 'easy',
    category: 'المصفوفات',
    points: 1,
  },
  // === معلومات عامة ===
  {
    id: 'b25',
    question: 'ما هي ميزة لغة المرجع الرئيسية؟',
    options: ['دعم عربي كامل', 'سرعة فائقة فقط', 'سهولة التعلم فقط', 'حجم صغير'],
    correctAnswer: 0,
    explanation: 'لغة المرجع هي أول لغة برمجة عربية متكاملة مع الذكاء الاصطناعي مع دعم عربي كامل.',
    difficulty: 'easy',
    category: 'معلومات عامة',
    points: 1,
  },
  {
    id: 'b26',
    question: 'ما هي اللغة التي بُنيت بها لغة المرجع؟',
    options: ['Rust', 'Python', 'C++', 'Go'],
    correctAnswer: 0,
    explanation: 'لغة المرجع بُنيت باستخدام Rust للحصول على أداء عالٍ وأمان.',
    difficulty: 'easy',
    category: 'معلومات عامة',
    points: 1,
  },
  {
    id: 'b27',
    question: 'ما هو Vibe Coding؟',
    options: ['البرمجة باللغة الطبيعية', 'برمجة الألعاب', 'برمجة الويب', 'برمجة الأنظمة'],
    correctAnswer: 0,
    explanation: 'Vibe Coding هي ميزة ثورية تتيح البرمجة باللغة الطبيعية العربية.',
    difficulty: 'easy',
    category: 'Vibe Coding',
    points: 1,
  },
  {
    id: 'b28',
    question: 'كيف تُكتب الدالة الرئيسية في لغة المرجع؟',
    options: ['دالة رئيسي()', 'function main()', 'def main():', 'int main()'],
    correctAnswer: 0,
    explanation: 'الدالة الرئيسية تُعرّف بـ "دالة رئيسي()" وتُنفذ عند تشغيل البرنامج.',
    difficulty: 'easy',
    category: 'الدوال',
    points: 1,
  },
  {
    id: 'b29',
    question: 'من هو مؤسس لغة المرجع؟',
    options: ['رضوان دالي حمدوني', 'مؤسس مجهول', 'شركة أجنبية', 'جمعية مفتوحة'],
    correctAnswer: 0,
    explanation: 'رضوان دالي حمدوني هو مؤسس لغة المرجع.',
    difficulty: 'easy',
    category: 'معلومات عامة',
    points: 1,
  },
  {
    id: 'b30',
    question: 'ما هو البريد الرسمي لمشروع المرجع؟',
    options: ['almarjaa.project@hotmail.com', 'info@almarjaa.com', 'support@marjaa.net', 'contact@almarjaa.org'],
    correctAnswer: 0,
    explanation: 'البريد الرسمي للمشروع هو almarjaa.project@hotmail.com.',
    difficulty: 'easy',
    category: 'معلومات عامة',
    points: 1,
  },
  {
    id: 'b31',
    question: 'ما معنى "المرجع" في لغة البرمجة؟',
    options: ['المصدر والمرجعية', 'لغة مرجعية فقط', 'اسم عشوائي', 'اختصار لكلمة'],
    correctAnswer: 0,
    explanation: 'المرجع تعني المصدر والمرجعية في البرمجة العربية.',
    difficulty: 'easy',
    category: 'معلومات عامة',
    points: 1,
  },
  {
    id: 'b32',
    question: 'كيف تُقرأ قيمة من المستخدم؟',
    options: ['اقرأ()', 'input()', 'scanf()', 'readline()'],
    correctAnswer: 0,
    explanation: 'دالة "اقرأ" تُستخدم لقراءة المدخلات من المستخدم.',
    difficulty: 'easy',
    category: 'الإدخال والإخراج',
    points: 1,
  },
  {
    id: 'b33',
    question: 'ما ناتج: اطبع(2 + 3 * 2)؟',
    options: ['8', '10', '12', '7'],
    correctAnswer: 0,
    explanation: 'الضرب له الأولوية: 3 * 2 = 6، ثم 2 + 6 = 8.',
    difficulty: 'easy',
    category: 'العمليات الحسابية',
    points: 1,
  },
  {
    id: 'b34',
    question: 'ما الفرق بين = و ==؟',
    options: ['= للإسناد و == للمقارنة', '= للمقارنة و == للإسناد', 'لا فرق', '= للطباعة'],
    correctAnswer: 0,
    explanation: '= يُستخدم لإسناد قيمة لمتغير، و == للمقارنة بين قيمتين.',
    difficulty: 'easy',
    category: 'عمليات المقارنة',
    points: 1,
  },
  {
    id: 'b35',
    question: 'ما نوع القيمة: [1، 2، 3]؟',
    options: ['مصفوفة', 'قائمة', 'مجموعة', 'سجل'],
    correctAnswer: 0,
    explanation: 'القيم بين أقواس مربعة هي مصفوفات في لغة المرجع.',
    difficulty: 'easy',
    category: 'أنواع البيانات',
    points: 1,
  },
  {
    id: 'b36',
    question: 'كيف تتحقق إذا كان المتغير فارغاً؟',
    options: ['المتغير == فارغ', 'المتغير == null', 'المتغير == none', 'empty(المتغير)'],
    correctAnswer: 0,
    explanation: 'نستخدم "فارغ" للتحقق من القيمة الفارغة.',
    difficulty: 'medium',
    category: 'القيم الفارغة',
    points: 2,
  },
  {
    id: 'b37',
    question: 'ما هو طول المصفوفة [أ، ب، ج]؟',
    options: ['3', '2', '4', 'خطأ'],
    correctAnswer: 0,
    explanation: 'المصفوفة تحتوي على 3 عناصر، طولها 3.',
    difficulty: 'easy',
    category: 'المصفوفات',
    points: 1,
  },
  {
    id: 'b38',
    question: 'كيف تُعرّف متغيراً بدون قيمة ابتدائية؟',
    options: ['متغير العدد: عدد_صحيح؛', 'var number: int;', 'متغير العدد = فارغ؛', 'int number;'],
    correctAnswer: 0,
    explanation: 'يمكن تعريف متغير مع نوعه فقط بدون قيمة ابتدائية.',
    difficulty: 'medium',
    category: 'المتغيرات',
    points: 2,
  },
  {
    id: 'b39',
    question: 'ما ناتج: "مرحباً".طول؟',
    options: ['6', '5', '7', 'خطأ'],
    correctAnswer: 0,
    explanation: 'كلمة "مرحباً" تحتوي على 6 حروف (مع التشكيلة).',
    difficulty: 'medium',
    category: 'النصوص',
    points: 2,
  },
  {
    id: 'b40',
    question: 'ما هي كلمة "راجع" في لغة المرجع؟',
    options: ['تعيد قيمة من دالة', 'تنهي البرنامج', 'تطبع قيمة', 'تُعرّف متغيراً'],
    correctAnswer: 0,
    explanation: 'كلمة "راجع" أو "أرجع" تُستخدم لإرجاع قيمة من الدالة.',
    difficulty: 'easy',
    category: 'الدوال',
    points: 1,
  },
  // === أسئلة إضافية للمبتدئين ===
  {
    id: 'b41',
    question: 'ماذا يُطبع: اطبع("السلام" + " عليكم")؟',
    options: ['السلام عليكم', 'السلامعليكم', 'خطأ', '"السلام" "عليكم"'],
    correctAnswer: 0,
    explanation: 'عملية + تدمج النصوص مع المسافة الموجودة.',
    difficulty: 'easy',
    category: 'النصوص',
    points: 1,
  },
  {
    id: 'b42',
    question: 'ما هي نتيجة: صحيح و خطأ؟',
    options: ['خطأ', 'صحيح', 'خطأ في الصيغة', 'غير محدد'],
    correctAnswer: 0,
    explanation: 'عملية "و" المنطقية تُرجع خطأ إذا كان أحد المعاملين خطأ.',
    difficulty: 'medium',
    category: 'العمليات المنطقية',
    points: 2,
  },
  {
    id: 'b43',
    question: 'ما هي نتيجة: صحيح أو خطأ؟',
    options: ['صحيح', 'خطأ', 'خطأ في الصيغة', 'غير محدد'],
    correctAnswer: 0,
    explanation: 'عملية "أو" المنطقية تُرجع صحيح إذا كان أحد المعاملين صحيح.',
    difficulty: 'medium',
    category: 'العمليات المنطقية',
    points: 2,
  },
  {
    id: 'b44',
    question: 'ما هي نتيجة: ليس صحيح؟',
    options: ['خطأ', 'صحيح', 'غير محدد', 'خطأ في الصيغة'],
    correctAnswer: 0,
    explanation: 'عملية "ليس" تقلب القيمة المنطقية.',
    difficulty: 'medium',
    category: 'العمليات المنطقية',
    points: 2,
  },
  {
    id: 'b45',
    question: 'كيف تُحوّل النص "123" لعدد؟',
    options: ['رقم("123")', 'int("123")', 'عدد("123")', 'convert("123")'],
    correctAnswer: 0,
    explanation: 'دالة "رقم" تُحوّل النص لعدد.',
    difficulty: 'medium',
    category: 'التحويل بين الأنواع',
    points: 2,
  },
  {
    id: 'b46',
    question: 'كيف تُحوّل العدد 123 لنص؟',
    options: ['نص(123)', 'string(123)', 'str(123)', 'toString(123)'],
    correctAnswer: 0,
    explanation: 'دالة "نص" تُحوّل القيمة لنص.',
    difficulty: 'medium',
    category: 'التحويل بين الأنواع',
    points: 2,
  },
  {
    id: 'b47',
    question: 'ما الفرق بين 10 / 3 و 10 // 3؟',
    options: ['الأولى تعطي 3.33 والثانية 3', 'لا فرق', 'الأولى 3 والثانية 3.33', 'كلاهما خطأ'],
    correctAnswer: 0,
    explanation: '/ قسمة عادية تعطي ناتج عشري، // قسمة صحيحة تعطي الناتج الصحيح فقط.',
    difficulty: 'medium',
    category: 'العمليات الحسابية',
    points: 2,
  },
  {
    id: 'b48',
    question: 'ما هو ناتج: 10 ** 0؟',
    options: ['1', '0', '10', 'خطأ'],
    correctAnswer: 0,
    explanation: 'أي عدد أس صفر يساوي 1.',
    difficulty: 'medium',
    category: 'العمليات الحسابية',
    points: 2,
  },
  {
    id: 'b49',
    question: 'ما هي نتيجة: 5 < 3؟',
    options: ['خطأ', 'صحيح', '5', '3'],
    correctAnswer: 0,
    explanation: '5 ليس أصغر من 3، فالنتيجة خطأ.',
    difficulty: 'easy',
    category: 'عمليات المقارنة',
    points: 1,
  },
  {
    id: 'b50',
    question: 'ما هي نتيجة: 5 != 5؟',
    options: ['خطأ', 'صحيح', '0', '5'],
    correctAnswer: 0,
    explanation: '5 يساوي 5، فـ "لا يساوي" تُرجع خطأ.',
    difficulty: 'easy',
    category: 'عمليات المقارنة',
    points: 1,
  },
];

// ============================================
// أسئلة المستوى المتوسط - Intermediate Questions (60+ سؤال)
// ============================================

export const intermediateQuestions: Question[] = [
  // === الدوال ===
  {
    id: 'i1',
    question: 'كيف تُعرّف دالة تستقبل معامل وترجع قيمة؟',
    options: ['دالة اسم_الدالة(المعامل) { أرجع القيمة؛ }', 'function name(param) { return value; }', 'def name(param): return value', 'func name(param) -> value'],
    correctAnswer: 0,
    explanation: 'الدوال تُعرّف بـ "دالة" وتستخدم "أرجع" لإرجاع القيم.',
    difficulty: 'medium',
    category: 'الدوال',
    points: 2,
  },
  {
    id: 'i2',
    question: 'ما الكلمة المفتاحية لإرجاع قيمة من دالة؟',
    options: ['أرجع', 'return', 'إرجاع', 'أعطي'],
    correctAnswer: 0,
    explanation: 'نستخدم "أرجع" لإرجاع القيم من الدوال.',
    difficulty: 'easy',
    category: 'الدوال',
    points: 1,
  },
  {
    id: 'i3',
    question: 'كيف تستدعي دالة؟',
    options: ['اسم_الدالة(المعاملات)؛', 'call اسم_الدالة()', 'اسم_الدالة.call()', 'run اسم_الدالة()'],
    correctAnswer: 0,
    explanation: 'استدعاء الدالة يتم بكتابة اسمها وأقواس تحتوي على المعاملات.',
    difficulty: 'easy',
    category: 'الدوال',
    points: 1,
  },
  {
    id: 'i4',
    question: 'ما هي الدالة البناءة (Constructor)؟',
    options: ['دالة تُنفذ عند إنشاء كائن', 'دالة للطباعة', 'دالة للحذف', 'دالة للنسخ'],
    correctAnswer: 0,
    explanation: 'الدالة البناءة تُنفذ تلقائياً عند إنشاء كائن جديد من الصنف.',
    difficulty: 'medium',
    category: 'البرمجة الكائنية',
    points: 2,
  },
  // === الحلقات ===
  {
    id: 'i5',
    question: 'كيف تُكتب حلقة تكرار من 1 إلى 10؟',
    options: ['لكل رقم في مدى(1، 10) { }', 'for i in range(1, 10):', 'for (i = 1; i <= 10; i++) { }', 'loop i from 1 to 10:'],
    correctAnswer: 0,
    explanation: 'الحلقة "لكل" مع "مدى" تُستخدم للتكرار على نطاق من الأرقام.',
    difficulty: 'medium',
    category: 'الحلقات',
    points: 2,
  },
  {
    id: 'i6',
    question: 'ما هي الكلمة المفتاحية للخروج من حلقة؟',
    options: ['اخرج', 'break', 'توقف', 'خروج'],
    correctAnswer: 0,
    explanation: '"اخرج" تُستخدم للخروج المبكر من الحلقات.',
    difficulty: 'easy',
    category: 'الحلقات',
    points: 1,
  },
  {
    id: 'i7',
    question: 'ما هي الكلمة المفتاحية للتخطي للتكرار التالي؟',
    options: ['تخطي', 'continue', 'التالي', 'skip'],
    correctAnswer: 0,
    explanation: '"تخطي" تتجاوز التكرار الحالي وتنتقل للتكرار التالي.',
    difficulty: 'easy',
    category: 'الحلقات',
    points: 1,
  },
  {
    id: 'i8',
    question: 'ما هي حلقة "طالما"؟',
    options: ['حلقة تتنفذ طالما الشرط صحيح', 'حلقة محددة العدد', 'حلقة لا نهائية', 'دالة تكرار'],
    correctAnswer: 0,
    explanation: 'حلقة "طالما" تتنفذ طالما الشرط صحيح (while loop).',
    difficulty: 'medium',
    category: 'الحلقات',
    points: 2,
  },
  {
    id: 'i9',
    question: 'ما الفرق بين "لكل" و "طالما"؟',
    options: ['لكل للتكرار المحدد، طالما للشرطي', 'لا فرق', 'لكل للشرطي، طالما للمحدد', 'كلاهما متشابهان'],
    correctAnswer: 0,
    explanation: '"لكل" تُستخدم للتكرار على نطاق أو مصفوفة، "طالما" للتكرار حسب شرط.',
    difficulty: 'medium',
    category: 'الحلقات',
    points: 2,
  },
  // === الشروط ===
  {
    id: 'i10',
    question: 'كيف تُكتب جملة شرطية بسيطة؟',
    options: ['إذا الشرط { }', 'if condition { }', 'when condition:', 'case condition:'],
    correctAnswer: 0,
    explanation: 'الشرطية تُكتب بـ "إذا" متبوعة بالشرط والأقواس.',
    difficulty: 'easy',
    category: 'الشروط',
    points: 1,
  },
  {
    id: 'i11',
    question: 'ما الكلمة المفتاحية للشرط البديل (else)؟',
    options: ['وإلا', 'else', 'غير', 'خلاف'],
    correctAnswer: 0,
    explanation: '"وإلا" تُستخدم للكتلة البديلة في الشرطيات.',
    difficulty: 'easy',
    category: 'الشروط',
    points: 1,
  },
  {
    id: 'i12',
    question: 'كيف تُكتب شرطية متعددة الفروع؟',
    options: ['إذا الشرط1 { } وإلا_إذا الشرط2 { } وإلا { }', 'if cond1 {} else if cond2 {} else {}', 'if cond1: elif cond2: else:', 'case when cond1: when cond2: else:'],
    correctAnswer: 0,
    explanation: 'نستخدم "إلا_إذا" للفروع الإضافية و "وإلا" للفرع الافتراضي.',
    difficulty: 'medium',
    category: 'الشروط',
    points: 2,
  },
  {
    id: 'i13',
    question: 'ما هي بنية "اختر" (switch)؟',
    options: ['اختر المتغير { حالة 1: ... حالة 2: ... }', 'switch(var) { case 1: ... }', 'match var { 1 => ... }', 'case var of 1: ...'],
    correctAnswer: 0,
    explanation: 'بنية "اختر" تُستخدم للفحص المتعدد لحالات قيمة واحدة.',
    difficulty: 'medium',
    category: 'الشروط',
    points: 2,
  },
  // === المصفوفات المتقدمة ===
  {
    id: 'i14',
    question: 'كيف تحصل على عدد عناصر المصفوفة؟',
    options: ['المصفوفة.طول', 'length(المصفوفة)', 'len(المصفوفة)', 'المصفوفة.عدد'],
    correctAnswer: 0,
    explanation: 'الخاصية "طول" تُرجع عدد العناصر في المصفوفة.',
    difficulty: 'easy',
    category: 'المصفوفات',
    points: 1,
  },
  {
    id: 'i15',
    question: 'كيف تضيف عنصراً لنهاية مصفوفة؟',
    options: ['المصفوفة.أضف(العنصر)', 'المصفوفة.push(العنصر)', 'المصفوفة += العنصر', 'أضف(المصفوفة، العنصر)'],
    correctAnswer: 0,
    explanation: 'الدالة "أضف" تضيف عنصراً جديداً لنهاية المصفوفة.',
    difficulty: 'easy',
    category: 'المصفوفات',
    points: 1,
  },
  {
    id: 'i16',
    question: 'كيف تحذف عنصراً من مصفوفة؟',
    options: ['المصفوفة.احذف(الفهرس)', 'المصفوفة.remove(index)', 'delete المصفوفة[index]', 'المصفوفة -= العنصر'],
    correctAnswer: 0,
    explanation: 'دالة "احذف" تُزيل العنصر في الفهرس المحدد.',
    difficulty: 'medium',
    category: 'المصفوفات',
    points: 2,
  },
  {
    id: 'i17',
    question: 'كيف تبحث عن عنصر في مصفوفة؟',
    options: ['المصفوفة.ابحث(العنصر)', 'المصفوفة.find(element)', 'المصفوفة.indexOf(element)', 'search(المصفوفة، element)'],
    correctAnswer: 0,
    explanation: 'دالة "ابحث" تُرجع فهرس العنصر أو -1 إذا لم يوجد.',
    difficulty: 'medium',
    category: 'المصفوفات',
    points: 2,
  },
  // === البرمجة الكائنية ===
  {
    id: 'i18',
    question: 'كيف تُعرّف صنفاً (class) جديد؟',
    options: ['صنف الاسم { }', 'class الاسم { }', 'type الاسم = { }', 'struct الاسم { }'],
    correctAnswer: 0,
    explanation: 'الأصناف تُعرّف بـ "صنف" في لغة المرجع.',
    difficulty: 'medium',
    category: 'البرمجة الكائنية',
    points: 2,
  },
  {
    id: 'i19',
    question: 'ما الكلمة المفتاحية للإشارة للكائن الحالي؟',
    options: ['هذا', 'self', 'this', 'أنا'],
    correctAnswer: 0,
    explanation: '"هذا" تُستخدم للإشارة للكائن الحالي داخل الصنف.',
    difficulty: 'easy',
    category: 'البرمجة الكائنية',
    points: 1,
  },
  {
    id: 'i20',
    question: 'ما هي الخاصية في الصنف؟',
    options: ['متغير داخل الصنف', 'دالة داخل الصنف', 'معامل الصنف', 'اسم الصنف'],
    correctAnswer: 0,
    explanation: 'الخاصية هي متغير يُعرّف داخل الصنف ويخزن بيانات الكائن.',
    difficulty: 'medium',
    category: 'البرمجة الكائنية',
    points: 2,
  },
  {
    id: 'i21',
    question: 'ما هو التابع (Method)؟',
    options: ['دالة داخل الصنف', 'متغير داخل الصنف', 'معامل الصنف', 'اسم الصنف'],
    correctAnswer: 0,
    explanation: 'التابع هو دالة تُعرّف داخل الصنف وتُنفذ على الكائنات.',
    difficulty: 'medium',
    category: 'البرمجة الكائنية',
    points: 2,
  },
  {
    id: 'i22',
    question: 'كيف تُنشئ كائناً من صنف؟',
    options: ['كائن اسم = الصنف()؛', 'new الصنف()', 'الصنف.create()', 'make الصنف()'],
    correctAnswer: 0,
    explanation: 'يُنشأ كائن باستدعاء الصنف كدالة.',
    difficulty: 'medium',
    category: 'البرمجة الكائنية',
    points: 2,
  },
  // === معالجة الأخطاء ===
  {
    id: 'i23',
    question: 'كيف تتعامل مع الأخطاء المحتملة؟',
    options: ['حاول { } أمسك (خطأ) { }', 'try { } catch (e) { }', 'try: except:', 'handle error:'],
    correctAnswer: 0,
    explanation: 'نستخدم "حاول" و "أمسك" لمعالجة الأخطاء.',
    difficulty: 'medium',
    category: 'معالجة الأخطاء',
    points: 2,
  },
  {
    id: 'i24',
    question: 'كيف تُطلق استثناءً؟',
    options: ['ارفع("الخطأ")', 'throw "الخطأ"', 'raise "الخطأ"', 'خطأ("الخطأ")'],
    correctAnswer: 0,
    explanation: '"ارفع" تُستخدم لإطلاق الاستثناءات.',
    difficulty: 'medium',
    category: 'معالجة الأخطاء',
    points: 2,
  },
  {
    id: 'i25',
    question: 'ما هي الكتلة "أخيراً"؟',
    options: ['تُنفذ دائماً بعد حاول', 'تُنفذ عند الخطأ فقط', 'تُنفذ عند النجاح فقط', 'لا تُستخدم'],
    correctAnswer: 0,
    explanation: 'كتلة "أخيراً" تُنفذ دائماً سواء حدث خطأ أم لا.',
    difficulty: 'medium',
    category: 'معالجة الأخطاء',
    points: 2,
  },
  // === المزيد من الأسئلة ===
  {
    id: 'i26',
    question: 'ما هي نتيجة: مدى(1، 5)؟',
    options: ['[1، 2، 3، 4]', '[1، 2، 3، 4، 5]', '[0، 1، 2، 3، 4]', '[2، 3، 4]'],
    correctAnswer: 0,
    explanation: 'مدى(1، 5) يُنشئ نطاقاً من 1 إلى 4 (غير شامل النهاية).',
    difficulty: 'medium',
    category: 'النطاقات',
    points: 2,
  },
  {
    id: 'i27',
    question: 'كيف تُعرّف دالة بمعامل افتراضي؟',
    options: ['دالة الاسم(المعامل = القيمة) { }', 'function name(param = value) { }', 'def name(param=value):', 'func name(param: value) {}'],
    correctAnswer: 0,
    explanation: 'المعاملات الافتراضية تُحدد بـ = عند تعريف الدالة.',
    difficulty: 'medium',
    category: 'الدوال',
    points: 2,
  },
  {
    id: 'i28',
    question: 'ما هي الدالة المجهولة (Lambda)؟',
    options: ['دالة بدون اسم تُعرّف في مكانها', 'دالة سرية', 'دالة محذوفة', 'دالة مخفية'],
    correctAnswer: 0,
    explanation: 'الدالة المجهولة تُعرّف بدون اسم وتُستخدم مباشرة.',
    difficulty: 'hard',
    category: 'الدوال المتقدمة',
    points: 3,
  },
  {
    id: 'i29',
    question: 'ما هي الإغلاقيات (Closures)؟',
    options: ['دوال تحتفظ بمتغيرات من نطاقها الخارجي', 'دوال مغلقة', 'دوال محذوفة', 'ملفات مغلقة'],
    correctAnswer: 0,
    explanation: 'الإغلاقية هي دالة تتذكر المتغيرات من النطاق الذي عُرّفت فيه.',
    difficulty: 'hard',
    category: 'الدوال المتقدمة',
    points: 3,
  },
  {
    id: 'i30',
    question: 'كيف تُستخدم دالة كمعامل؟',
    options: ['دالة(دالة_أخرى)', 'function(function)', 'دالة_أخرى as param', 'pass دالة_أخرى'],
    correctAnswer: 0,
    explanation: 'الدوال يمكن تمريرها كمعاملات لدوال أخرى.',
    difficulty: 'hard',
    category: 'الدوال المتقدمة',
    points: 3,
  },
  // === النصوص المتقدمة ===
  {
    id: 'i31',
    question: 'كيف تقطع نصاً من الموضع 2 إلى 5؟',
    options: ['النص[2:5]', 'النص.substring(2, 5)', 'النص.قطع(2، 5)', 'substring(النص، 2، 5)'],
    correctAnswer: 0,
    explanation: 'التقطيع [البداية:النهاية] يُرجع جزءاً من النص.',
    difficulty: 'medium',
    category: 'النصوص',
    points: 2,
  },
  {
    id: 'i32',
    question: 'كيف تبحث عن نص داخل نص؟',
    options: ['النص.يحتوي("البحث")', 'النص.includes("search")', 'النص.find("search")', 'contains(النص، "search")'],
    correctAnswer: 0,
    explanation: 'دالة "يحتوي" تتحقق من وجود نص داخل نص آخر.',
    difficulty: 'medium',
    category: 'النصوص',
    points: 2,
  },
  {
    id: 'i33',
    question: 'كيف تستبدل نصاً بنص آخر؟',
    options: ['النص.استبدل("القديم"، "الجديد")', 'النص.replace("old", "new")', 'replace(النص، "old"، "new")', 'النص.swap("old", "new")'],
    correctAnswer: 0,
    explanation: 'دالة "استبدل" تُبدل جميع وجودات النص القديم بالجديد.',
    difficulty: 'medium',
    category: 'النصوص',
    points: 2,
  },
  {
    id: 'i34',
    question: 'كيف تُقسم نصاً بكلمة فاصلة؟',
    options: ['النص.اقسم(" ")', 'النص.split(" ")', 'split(النص، " ")', 'النص.divide(" ")'],
    correctAnswer: 0,
    explanation: 'دالة "اقسم" تُقسم النص لمصفوفة حسب الفاصل.',
    difficulty: 'medium',
    category: 'النصوص',
    points: 2,
  },
  {
    id: 'i35',
    question: 'كيف تدمج مصفوفة نصوص في نص واحد؟',
    options: ['المصفوفة.ادمج(" ")', 'المصفوفة.join(" ")', 'join(المصفوفة، " ")', 'المصفوفة.concat(" ")'],
    correctAnswer: 0,
    explanation: 'دالة "ادمج" تدمج عناصر المصفوفة في نص واحد بالفاصل المحدد.',
    difficulty: 'medium',
    category: 'النصوص',
    points: 2,
  },
  // === القواميس ===
  {
    id: 'i36',
    question: 'ما هو القاموس (Dictionary)؟',
    options: ['مجموعة أزواج مفتاح-قيمة', 'مصفوفة مرقمة', 'قائمة نصية', 'سجل مرتب'],
    correctAnswer: 0,
    explanation: 'القاموس يخزن بيانات على شكل أزواج مفتاح-قيمة.',
    difficulty: 'medium',
    category: 'القواميس',
    points: 2,
  },
  {
    id: 'i37',
    question: 'كيف تُعرّف قاموساً فارغاً؟',
    options: ['{}', '[]', '()', '<>'],
    correctAnswer: 0,
    explanation: 'القواميس تُعرّف بأقواس معقوفة {}.',
    difficulty: 'easy',
    category: 'القواميس',
    points: 1,
  },
  {
    id: 'i38',
    question: 'كيف تصل لقيمة في قاموس؟',
    options: ['القاموس["المفتاح"]', 'القاموس.المفتاح', 'القاموس(المفتاح)', 'القاموس->المفتاح'],
    correctAnswer: 0,
    explanation: 'الوصول للقيمة يتم بالمفتاح بين أقواس مربعة.',
    difficulty: 'easy',
    category: 'القواميس',
    points: 1,
  },
  {
    id: 'i39',
    question: 'كيف تضيف زوجاً جديداً للقاموس؟',
    options: ['القاموس["المفتاح"] = القيمة؛', 'القاموس.add("key", value)', 'القاموس.أضف("المفتاح"، القيمة)', 'add(القاموس، "key"، value)'],
    correctAnswer: 0,
    explanation: 'إضافة زوج جديد تتم بالإسناد المباشر.',
    difficulty: 'medium',
    category: 'القواميس',
    points: 2,
  },
  {
    id: 'i40',
    question: 'كيف تتحقق من وجود مفتاح في قاموس؟',
    options: ['"المفتاح" في القاموس', 'القاموس.has("key")', 'القاموس.contains("key")', 'exists(القاموس، "key")'],
    correctAnswer: 0,
    explanation: 'كلمة "في" تتحقق من وجود المفتاح في القاموس.',
    difficulty: 'medium',
    category: 'القواميس',
    points: 2,
  },
  // === الوحدات ===
  {
    id: 'i41',
    question: 'كيف تستورد وحدة (module)؟',
    options: ['استورد "الوحدة"؛', 'import module;', 'require "module"', 'include "module"'],
    correctAnswer: 0,
    explanation: 'كلمة "استورد" تُستخدم لاستيراد الوحدات.',
    difficulty: 'medium',
    category: 'الوحدات',
    points: 2,
  },
  {
    id: 'i42',
    question: 'كيف تُصدّر دالة من وحدة؟',
    options: ['صدّر الدالة؛', 'export function;', 'module.exports = function', 'public function'],
    correctAnswer: 0,
    explanation: 'كلمة "صدّر" تُستخدم لتصدير الدوال والقيم من الوحدة.',
    difficulty: 'medium',
    category: 'الوحدات',
    points: 2,
  },
  {
    id: 'i43',
    question: 'ما هي ميزة استخدام الوحدات؟',
    options: ['تنظيم الكود وإعادة الاستخدام', 'زيادة السرعة فقط', 'تقليل الحجم فقط', 'لا فائدة'],
    correctAnswer: 0,
    explanation: 'الوحدات تُنظّم الكود وتسمح بإعادة استخدامه في مشاريع مختلفة.',
    difficulty: 'easy',
    category: 'الوحدات',
    points: 1,
  },
  // === أسئلة إضافية ===
  {
    id: 'i44',
    question: 'ما هي الوراثة في البرمجة الكائنية؟',
    options: ['اكتساب خصائص صنف آخر', 'نسخ الأصناف', 'حذف الأصناف', 'دمج الأصناف'],
    correctAnswer: 0,
    explanation: 'الوراثة تتيح للصنف اكتساب خصائص ودوال صنف آخر.',
    difficulty: 'medium',
    category: 'البرمجة الكائنية',
    points: 2,
  },
  {
    id: 'i45',
    question: 'كيف تعرّف صنفاً يرث من صنف آخر؟',
    options: ['صنف الابن يرث الأب { }', 'class Son extends Father { }', 'صنف الابن : الأب { }', 'type Son = Father + {}'],
    correctAnswer: 0,
    explanation: 'الكلمة "يرث" تُستخدم لتعريف الوراثة بين الأصناف.',
    difficulty: 'medium',
    category: 'البرمجة الكائنية',
    points: 2,
  },
  {
    id: 'i46',
    question: 'ما هو التغليف (Encapsulation)؟',
    options: ['إخفاء التفاصيل الداخلية للصنف', 'نسخ الصنف', 'حذف الصنف', 'دمج الأصناف'],
    correctAnswer: 0,
    explanation: 'التغليف يُخفي التفاصيل الداخلية ويُظهر فقط الواجهة المطلوبة.',
    difficulty: 'medium',
    category: 'البرمجة الكائنية',
    points: 2,
  },
  {
    id: 'i47',
    question: 'ما هو تعدد الأشكال (Polymorphism)؟',
    options: ['قدرة الدوال على العمل بأشكال مختلفة', 'تعدد المتغيرات', 'تعدد الملفات', 'تعدد الوحدات'],
    correctAnswer: 0,
    explanation: 'تعدد الأشكال يسمح لنفس الدالة بالتصرف بشكل مختلف حسب السياق.',
    difficulty: 'hard',
    category: 'البرمجة الكائنية',
    points: 3,
  },
  {
    id: 'i48',
    question: 'ما هي الواجهة (Interface)؟',
    options: ['تعريف للدوال والخصائص بدون تنفيذ', 'صنف مكتمل', 'دالة مجهولة', 'وحدة برمجية'],
    correctAnswer: 0,
    explanation: 'الواجهة تُعرّف الدوال والخصائص المطلوبة بدون تنفيذها.',
    difficulty: 'hard',
    category: 'البرمجة الكائنية',
    points: 3,
  },
  {
    id: 'i49',
    question: 'ما هو التجريد (Abstraction)؟',
    options: ['تبسيط الأنظمة المعقدة بإخفاء التفاصيل', 'إنشاء أصناف', 'حذف الأصناف', 'نسخ الأصناف'],
    correctAnswer: 0,
    explanation: 'التجريد يُبسّط الأنظمة المعقدة بإخفاء التفاصيل غير المهمة.',
    difficulty: 'hard',
    category: 'البرمجة الكائنية',
    points: 3,
  },
  {
    id: 'i50',
    question: 'كيف تُعرّف واجهة؟',
    options: ['واجهة الاسم { }', 'interface Name { }', 'abstract class Name { }', 'protocol Name { }'],
    correctAnswer: 0,
    explanation: 'الواجهات تُعرّف بـ "واجهة" في لغة المرجع.',
    difficulty: 'hard',
    category: 'البرمجة الكائنية',
    points: 3,
  },
  // === المزيد ===
  {
    id: 'i51',
    question: 'ما هو التكرار (Recursion)؟',
    options: ['دالة تستدعي نفسها', 'دالة تستدعي دالة أخرى', 'حلقة تكرار', 'دالة مجهولة'],
    correctAnswer: 0,
    explanation: 'التكرار هو عندما تستدعي الدالة نفسها.',
    difficulty: 'medium',
    category: 'الدوال المتقدمة',
    points: 2,
  },
  {
    id: 'i52',
    question: 'ما هي حالة التوقف في التكرار؟',
    options: ['شرط يوقف استدعاء الدالة لنفسها', 'خطأ في التنفيذ', 'نهاية البرنامج', 'إرجاع قيمة'],
    correctAnswer: 0,
    explanation: 'حالة التوقف ضرورية لمنع التكرار اللانهائي.',
    difficulty: 'medium',
    category: 'الدوال المتقدمة',
    points: 2,
  },
  {
    id: 'i53',
    question: 'ما هي المشكلة في التكرار اللانهائي؟',
    options: ['يتسبب في تجميد البرنامج', 'يُسرع البرنامج', 'يُحسن الأداء', 'لا مشكلة فيه'],
    correctAnswer: 0,
    explanation: 'التكرار اللانهائي يُنفق الذاكرة ويُجمّد البرنامج.',
    difficulty: 'medium',
    category: 'الدوال المتقدمة',
    points: 2,
  },
  {
    id: 'i54',
    question: 'ما هي التعقيد الزمني (Time Complexity)؟',
    options: ['قياس وقت تنفيذ الخوارزمية', 'قياس حجم الكود', 'قياس عدد الأسطر', 'قياس الذاكرة'],
    correctAnswer: 0,
    explanation: 'التعقيد الزمني يُقيّم كفاءة الخوارزمية حسب وقت التنفيذ.',
    difficulty: 'hard',
    category: 'الخوارزميات',
    points: 3,
  },
  {
    id: 'i55',
    question: 'ما هو تعقيد البحث في مصفوفة غير مرتبة؟',
    options: ['O(n)', 'O(1)', 'O(log n)', 'O(n²)'],
    correctAnswer: 0,
    explanation: 'البحث في مصفوفة غير مرتبة يتطلب فحص كل عنصر في أسوأ حالة.',
    difficulty: 'hard',
    category: 'الخوارزميات',
    points: 3,
  },
  {
    id: 'i56',
    question: 'ما هو تعقيد البحث الثنائي؟',
    options: ['O(log n)', 'O(n)', 'O(1)', 'O(n²)'],
    correctAnswer: 0,
    explanation: 'البحث الثنائي يُقلّص نطاق البحث للنصف في كل خطوة.',
    difficulty: 'hard',
    category: 'الخوارزميات',
    points: 3,
  },
  {
    id: 'i57',
    question: 'ما شرط البحث الثنائي؟',
    options: ['المصفوفة يجب أن تكون مرتبة', 'المصفوفة يجب أن تكون فارغة', 'المصفوفة يجب أن تكون كبيرة', 'لا يوجد شرط'],
    correctAnswer: 0,
    explanation: 'البحث الثنائي يعمل فقط على المصفوفات المرتبة.',
    difficulty: 'medium',
    category: 'الخوارزميات',
    points: 2,
  },
  {
    id: 'i58',
    question: 'كيف تُرتّب مصفوفة في لغة المرجع؟',
    options: ['المصفوفة.رتّب()؛', 'المصفوفة.sort()', 'sort(المصفوفة)', 'المصفوفة.order()'],
    correctAnswer: 0,
    explanation: 'دالة "رتّب" تُرتّب عناصر المصفوفة تصاعدياً.',
    difficulty: 'medium',
    category: 'المصفوفات',
    points: 2,
  },
  {
    id: 'i59',
    question: 'كيف تقلب ترتيب مصفوفة؟',
    options: ['المصفوفة.اقلب()؛', 'المصفوفة.reverse()', 'reverse(المصفوفة)', 'المصفوفة.flip()'],
    correctAnswer: 0,
    explanation: 'دالة "اقلب" تُقلب ترتيب عناصر المصفوفة.',
    difficulty: 'medium',
    category: 'المصفوفات',
    points: 2,
  },
  {
    id: 'i60',
    question: 'ما هو الفلترة (Filter)؟',
    options: ['تصفية عناصر حسب شرط', 'ترتيب العناصر', 'حذف جميع العناصر', 'نسخ العناصر'],
    correctAnswer: 0,
    explanation: 'الفلترة تُبقي فقط العناصر التي تحقق الشرط.',
    difficulty: 'medium',
    category: 'المصفوفات',
    points: 2,
  },
];

// ============================================
// أسئلة المستوى المتقدم - Advanced Questions (60+ سؤال)
// ============================================

export const advancedQuestions: Question[] = [
  // === الذكاء الاصطناعي ===
  {
    id: 'a1',
    question: 'كيف تُنشئ شبكة عصبية في لغة المرجع؟',
    options: ['متغير شبكة = شبكة_عصبية()؛', 'import torch; model = nn.Network()', 'const network = new NeuralNetwork()', 'network = NeuralNetwork.create()'],
    correctAnswer: 0,
    explanation: 'شبكة_عصبية() تُنشئ شبكة عصبية جديدة في لغة المرجع.',
    difficulty: 'hard',
    category: 'الذكاء الاصطناعي',
    points: 3,
  },
  {
    id: 'a2',
    question: 'كيف تضيف طبقة للشبكة العصبية؟',
    options: ['شبكة.أضف_طبقة(128، "relu")؛', 'network.add_layer(128, "relu")', 'شبكة << طبقة(128, relu)', 'شبكة.add(Layer(128, relu))'],
    correctAnswer: 0,
    explanation: 'أضف_طبقة تضيف طبقة جديدة مع عدد الخلايا ودالة التنشيط.',
    difficulty: 'hard',
    category: 'الذكاء الاصطناعي',
    points: 3,
  },
  {
    id: 'a3',
    question: 'ما هي دالة التنشيط softmax المستخدمة لـ؟',
    options: ['طبقة الإخراج للتصنيف المتعدد', 'الطبقات المخفية فقط', 'تقليل overfitting', 'تسريع التدريب'],
    correctAnswer: 0,
    explanation: 'softmax تُستخدم في طبقة الإخراج للتصنيف المتعدد حيث تُحوّل المخرجات لاحتمالات.',
    difficulty: 'hard',
    category: 'الذكاء الاصطناعي',
    points: 3,
  },
  {
    id: 'a4',
    question: 'ما هي دالة التنشيط ReLU؟',
    options: ['دالة تُرجع 0 للقيم السالبة والقيمة نفسها للموجبة', 'دالة خطية دائماً', 'دالة تُرجع 1 دائماً', 'دالة حسابية'],
    correctAnswer: 0,
    explanation: 'ReLU تُرجع max(0, x) وتُستخدم على نطاق واسع في الشبكات العصبية.',
    difficulty: 'hard',
    category: 'الذكاء الاصطناعي',
    points: 3,
  },
  {
    id: 'a5',
    question: 'ما هو overfitting؟',
    options: ['حفظ النموذج لبيانات التدريب وعدم تعميمه', 'عدم تعلم النموذج أصلاً', 'تدريب سريع', 'حذف البيانات'],
    correctAnswer: 0,
    explanation: 'Overfitting يحدث عندما يحفظ النموذج بيانات التدريب بدلاً من تعلم الأنماط.',
    difficulty: 'hard',
    category: 'الذكاء الاصطناعي',
    points: 3,
  },
  // === Vibe Coding ===
  {
    id: 'a6',
    question: 'ما هو Vibe Coding في لغة المرجع؟',
    options: ['البرمجة باللغة الطبيعية العربية', 'برمجة الرسوم المتحركة', 'برمجة قواعد البيانات', 'برمجة الألعاب'],
    correctAnswer: 0,
    explanation: 'Vibe Coding هي ميزة ثورية تتيح كتابة الكود باللغة الطبيعية العربية.',
    difficulty: 'medium',
    category: 'Vibe Coding',
    points: 2,
  },
  {
    id: 'a7',
    question: 'ما نتيجة: "أنشئ متغير اسم يساوي أحمد"؟',
    options: ['متغير اسم = "أحمد"؛', 'var name = "أحmed";', 'let name := "أحمد"', 'name = "أحمد"'],
    correctAnswer: 0,
    explanation: 'Vibe Coding يُحوّل اللغة الطبيعية لكود لغة المرجع.',
    difficulty: 'medium',
    category: 'Vibe Coding',
    points: 2,
  },
  {
    id: 'a8',
    question: 'ما هي ميزة Vibe Coding الرئيسية؟',
    options: ['تقليل الفجوة بين الفكر والكود', 'زيادة سرعة الكتابة فقط', 'تقليل الأخطاء فقط', 'جميع ما سبق'],
    correctAnswer: 0,
    explanation: 'Vibe Coding تُقلّل الفجوة بين التفكير بالعربية وكتابة الكود.',
    difficulty: 'medium',
    category: 'Vibe Coding',
    points: 2,
  },
  // === ONNX ===
  {
    id: 'a9',
    question: 'ما هو ONNX؟',
    options: ['تنسيق مفتوح لنماذج الذكاء الاصطناعي', 'قاعدة بيانات', 'لغة برمجة', 'إطار عمل ويب'],
    correctAnswer: 0,
    explanation: 'ONNX (Open Neural Network Exchange) هو تنسيق لتبادل نماذج التعلم العميق.',
    difficulty: 'hard',
    category: 'ONNX',
    points: 3,
  },
  {
    id: 'a10',
    question: 'كيف تحمّل نموذج ONNX؟',
    options: ['نموذج = أونكس.حمّل("model.onnx")؛', 'model = onnx.load("model.onnx")', 'import onnx; model = load("model.onnx")', 'model := LoadONNX("model.onnx")'],
    correctAnswer: 0,
    explanation: 'أونكس.حمّل تحمّل نموذج ONNX للاستخدام في لغة المرجع.',
    difficulty: 'hard',
    category: 'ONNX',
    points: 3,
  },
  // === UI Framework ===
  {
    id: 'a11',
    question: 'كيف تُنشئ زراً في إطار عمل الواجهات؟',
    options: ['زر("اضغط هنا") { نقر: () => اطبع("تم")، }،', '<button onClick={print}>اضغط</button>', 'Button(text="اضغط", onClick=print)', 'new Button("اضغط", action: print)'],
    correctAnswer: 0,
    explanation: 'زر تُنشئ زراً مع نص ومعالج النقر.',
    difficulty: 'hard',
    category: 'واجهات المستخدم',
    points: 3,
  },
  {
    id: 'a12',
    question: 'ما هو الربط التلقائي للبيانات (Data Binding)؟',
    options: ['تحديث الواجهة تلقائياً عند تغيير البيانات', 'ربط قاعدة البيانات', 'ربط الملفات', 'ربط الشبكة'],
    correctAnswer: 0,
    explanation: 'الربط التلقائي يُحدّث الواجهة تلقائياً عند تغيير البيانات المرتبطة.',
    difficulty: 'hard',
    category: 'واجهات المستخدم',
    points: 3,
  },
  {
    id: 'a13',
    question: 'كيف تُعرّف متغيراً قابلاً للملاحظة للواجهة؟',
    options: ['متغير العدد = قابل_للملاحظة(0)؛', 'let count = observable(0)', '@observable count = 0', 'state count = 0'],
    correctAnswer: 0,
    explanation: 'قابل_للملاحظة تُنشئ متغيراً يُحدّث الواجهة تلقائياً عند تغييره.',
    difficulty: 'hard',
    category: 'واجهات المستخدم',
    points: 3,
  },
  // === الملفات ===
  {
    id: 'a14',
    question: 'كيف تقرأ محتوى ملف؟',
    options: ['محتوى = اقرأ_ملف("الملف.txt")؛', 'content = File.read("file.txt")', 'open("file.txt").read()', 'readFile("file.txt")'],
    correctAnswer: 0,
    explanation: 'اقرأ_ملف تقرأ محتوى ملف نصي وتُرجعه كسلسلة.',
    difficulty: 'medium',
    category: 'الملفات',
    points: 2,
  },
  {
    id: 'a15',
    question: 'كيف تكتب لملف؟',
    options: ['اكتب_ملف("الملف.txt"، "المحتوى")؛', 'File.write("file.txt", "content")', 'write("file.txt", "content")', 'echo "content" > file.txt'],
    correctAnswer: 0,
    explanation: 'اكتب_ملف تكتب محتوى نصي لملف.',
    difficulty: 'medium',
    category: 'الملفات',
    points: 2,
  },
  {
    id: 'a16',
    question: 'كيف تتحقق من وجود ملف؟',
    options: ['ملف_موجود("الملف.txt")', 'File.exists("file.txt")', 'exists("file.txt")', 'if file.txt exists'],
    correctAnswer: 0,
    explanation: 'دالة "ملف_موجود" تتحقق من وجود الملف.',
    difficulty: 'medium',
    category: 'الملفات',
    points: 2,
  },
  // === البرمجة غير المتزامنة ===
  {
    id: 'a17',
    question: 'ما هي البرمجة غير المتزامنة؟',
    options: ['تنفيذ العمليات دون انتظار اكتمالها', 'تنفيذ العمليات بالتوازي فقط', 'تنفيذ العمليات بالترتيب', 'إيقاف البرنامج'],
    correctAnswer: 0,
    explanation: 'البرمجة غير المتزامنة تتيح تنفيذ عمليات دون حظر البرنامج.',
    difficulty: 'hard',
    category: 'البرمجة غير المتزامنة',
    points: 3,
  },
  {
    id: 'a18',
    question: 'ما الكلمة المفتاحية للدالة غير المتزامنة؟',
    options: ['غير_متزامن', 'async', 'await', 'مؤجل'],
    correctAnswer: 0,
    explanation: '"غير_متزامن" تُعرّف دالة تعمل بشكل غير متزامن.',
    difficulty: 'hard',
    category: 'البرمجة غير المتزامنة',
    points: 3,
  },
  {
    id: 'a19',
    question: 'ما الكلمة المفتاحية للانتظار؟',
    options: ['انتظر', 'await', 'wait', 'pause'],
    correctAnswer: 0,
    explanation: '"انتظر" تُستخدم للانتظار حتى اكتمال العملية غير المتزامنة.',
    difficulty: 'hard',
    category: 'البرمجة غير المتزامنة',
    points: 3,
  },
  {
    id: 'a20',
    question: 'ما هو Promise؟',
    options: ['كائن يمثل نتيجة مستقبلية', 'دالة متزامنة', 'متغير عادي', 'صفيف خاص'],
    correctAnswer: 0,
    explanation: 'Promise يمثل قيمة ستكون متاحة في المستقبل.',
    difficulty: 'hard',
    category: 'البرمجة غير المتزامنة',
    points: 3,
  },
  // === JIT Compiler ===
  {
    id: 'a21',
    question: 'ما هو JIT Compiler؟',
    options: ['مُجمّع يُترجم الكود أثناء التنفيذ', 'مُجمّع مسبق', 'مُفسر عادي', 'مُحسن فقط'],
    correctAnswer: 0,
    explanation: 'JIT (Just-In-Time) يُترجم الكود للغة الآلة أثناء التنفيذ لتسريع الأداء.',
    difficulty: 'hard',
    category: 'الأداء',
    points: 3,
  },
  {
    id: 'a22',
    question: 'كم مستوى تحسين في JIT Compiler للغة المرجع؟',
    options: ['5 مستويات', '3 مستويات', '2 مستويات', '1 مستوى'],
    correctAnswer: 0,
    explanation: 'JIT Compiler له 5 مستويات تحسين من Tier 0 إلى Tier 4.',
    difficulty: 'expert',
    category: 'الأداء',
    points: 4,
  },
  {
    id: 'a23',
    question: 'ما هي نسبة التسريع التي يوفرها JIT Compiler؟',
    options: ['5.08x تسريع', '2x تسريع', '10x تسريع', '1.5x تسريع'],
    correctAnswer: 0,
    explanation: 'JIT Compiler يُسرّع الأداء بنسبة 5.08x مقارنة بالمفسر.',
    difficulty: 'expert',
    category: 'الأداء',
    points: 4,
  },
  {
    id: 'a24',
    question: 'كيف تُصدّر شبكة عصبية لـ ONNX؟',
    options: ['شبكة.صدّر("mymodel.onnx")؛', 'export(network, "mymodel.onnx")', 'torch.save(network, "mymodel.onnx")', 'network.save_onnx("mymodel.onnx")'],
    correctAnswer: 0,
    explanation: 'صدّر تُصدّر الشبكة العصبية لتنسيق ONNX للاستخدام في منصات أخرى.',
    difficulty: 'hard',
    category: 'ONNX',
    points: 3,
  },
  // === المزيد من الأسئلة المتقدمة ===
  {
    id: 'a25',
    question: 'ما هو SIMD Optimization؟',
    options: ['استخدام تعليمات المعالج المتوازية', 'تحسين الذاكرة', 'ضغط الكود', 'تسريع الشبكة'],
    correctAnswer: 0,
    explanation: 'SIMD (Single Instruction, Multiple Data) يُنفّذ نفس التعليمة على بيانات متعددة بالتوازي.',
    difficulty: 'expert',
    category: 'الأداء',
    points: 4,
  },
  {
    id: 'a26',
    question: 'ما هو Tracing JIT؟',
    options: ['تحسين المسارات الساخنة في الكود', 'تتبع الأخطاء', 'تتبع المستخدمين', 'تتبع الملفات'],
    correctAnswer: 0,
    explanation: 'Tracing JIT يُحسّن المسارات التي تُنفّذ كثيراً.',
    difficulty: 'expert',
    category: 'الأداء',
    points: 4,
  },
  {
    id: 'a27',
    question: 'ما هو التزامن (Concurrency)؟',
    options: ['تنفيذ مهام متعددة في نفس الوقت', 'تنفيذ مهمة واحدة', 'إيقاف التنفيذ', 'تنفيذ متسلسل'],
    correctAnswer: 0,
    explanation: 'التزامن يسمح بتنفيذ مهام متعددة بشكل متداخل.',
    difficulty: 'hard',
    category: 'البرمجة غير المتزامنة',
    points: 3,
  },
  {
    id: 'a28',
    question: 'ما هو التوازي (Parallelism)؟',
    options: ['تنفيذ مهام متعددة في نفس اللحظة', 'تنفيذ متسلسل', 'تنفيذ مهمة واحدة', 'إيقاف التنفيذ'],
    correctAnswer: 0,
    explanation: 'التوازي يُنفّذ مهام متعددة فعلياً في نفس اللحظة على معالجات متعددة.',
    difficulty: 'hard',
    category: 'البرمجة غير المتزامنة',
    points: 3,
  },
  {
    id: 'a29',
    question: 'ما هي سلاسل التنفيذ (Threads)؟',
    options: ['وحدات تنفيذ مستقلة داخل البرنامج', 'وحدات ذاكرة', 'ملفات', 'متغيرات'],
    correctAnswer: 0,
    explanation: 'سلاسل التنفيذ تسمح بتنفيذ كود متعدد بالتوازي.',
    difficulty: 'hard',
    category: 'البرمجة غير المتزامنة',
    points: 3,
  },
  {
    id: 'a30',
    question: 'ما هي المشكلة في التزامن؟',
    options: ['سباق البيانات والأقفال الميتة', 'لا توجد مشاكل', 'بطء التنفيذ', 'استهلاك الذاكرة'],
    correctAnswer: 0,
    explanation: 'التزامن قد يُسبب سباق بيانات وأقفال ميتة إذا لم يُدار بشكل صحيح.',
    difficulty: 'expert',
    category: 'البرمجة غير المتزامنة',
    points: 4,
  },
  // === الذاكرة ===
  {
    id: 'a31',
    question: 'ما هو جمع المهملات (Garbage Collection)؟',
    options: ['تحرير الذاكرة غير المستخدمة تلقائياً', 'تجميع الملفات', 'تجميع المتغيرات', 'تجميع الدوال'],
    correctAnswer: 0,
    explanation: 'Garbage Collection يُحرّر الذاكرة من الكائنات غير المستخدمة.',
    difficulty: 'hard',
    category: 'إدارة الذاكرة',
    points: 3,
  },
  {
    id: 'a32',
    question: 'ما هي تسرب الذاكرة (Memory Leak)؟',
    options: ['عدم تحرير ذاكرة لم تعد مستخدمة', 'زيادة الذاكرة', 'نقص الذاكرة', 'تحسين الذاكرة'],
    correctAnswer: 0,
    explanation: 'تسرب الذاكرة يحدث عند عدم تحرير ذاكرة غير مستخدمة.',
    difficulty: 'hard',
    category: 'إدارة الذاكرة',
    points: 3,
  },
  {
    id: 'a33',
    question: 'ما هي المراجع الدائرية؟',
    options: ['كائنان يشيران لبعضهما', 'مرجع لنفسه', 'مرجع فارغ', 'لا يوجد مرجع'],
    correctAnswer: 0,
    explanation: 'المراجع الدائرية قد تمنع جمع المهملات من تحرير الذاكرة.',
    difficulty: 'expert',
    category: 'إدارة الذاكرة',
    points: 4,
  },
  // === الشبكات ===
  {
    id: 'a34',
    question: 'كيف تُرسل طلب HTTP GET؟',
    options: ['طلب_HttpGet("الرابط")', 'fetch("url")', 'http.get("url")', 'request("url")'],
    correctAnswer: 0,
    explanation: 'دالة "طلب_HttpGet" تُرسل طلب GET للرابط المحدد.',
    difficulty: 'hard',
    category: 'الشبكات',
    points: 3,
  },
  {
    id: 'a35',
    question: 'كيف تُرسل طلب HTTP POST؟',
    options: ['طلب_HttpPost("الرابط"، البيانات)', 'http.post("url", data)', 'fetch("url", {method: "POST"})', 'request.post("url")'],
    correctAnswer: 0,
    explanation: 'دالة "طلب_HttpPost" تُرسل طلب POST مع البيانات.',
    difficulty: 'hard',
    category: 'الشبكات',
    points: 3,
  },
  {
    id: 'a36',
    question: 'ما هو JSON؟',
    options: ['تنسيق تبادل بيانات نصي', 'لغة برمجة', 'قاعدة بيانات', 'بروتوكول شبكة'],
    correctAnswer: 0,
    explanation: 'JSON هو تنسيق خفيف لتبادل البيانات.',
    difficulty: 'medium',
    category: 'البيانات',
    points: 2,
  },
  {
    id: 'a37',
    question: 'كيف تُحوّل نص JSON لكائن؟',
    options: ['json_حلل("النص")', 'JSON.parse("text")', 'parse_json("text")', 'json.decode("text")'],
    correctAnswer: 0,
    explanation: 'دالة "json_حلل" تُحوّل نص JSON لكائن.',
    difficulty: 'medium',
    category: 'البيانات',
    points: 2,
  },
  {
    id: 'a38',
    question: 'كيف تُحوّل كائن لنص JSON؟',
    options: ['json_نظم(الكائن)', 'JSON.stringify(obj)', 'to_json(obj)', 'json.encode(obj)'],
    correctAnswer: 0,
    explanation: 'دالة "json_نظم" تُحوّل الكائن لنص JSON.',
    difficulty: 'medium',
    category: 'البيانات',
    points: 2,
  },
  // === الاختبارات ===
  {
    id: 'a39',
    question: 'ما هي كتابة الاختبارات (Unit Testing)؟',
    options: ['اختبار وحدات الكود بشكل منفصل', 'اختبار البرنامج كاملاً', 'اختبار الواجهة', 'اختبار الأداء'],
    correctAnswer: 0,
    explanation: 'اختبارات الوحدات تختبر كل جزء من الكود بشكل مستقل.',
    difficulty: 'medium',
    category: 'الاختبارات',
    points: 2,
  },
  {
    id: 'a40',
    question: 'كيف تكتب اختباراً في لغة المرجع؟',
    options: ['اختبار "اسم_الاختبار" { ... }', 'test("name", () => {})', 'describe("name", () => {})', 'it("name", () => {})'],
    correctAnswer: 0,
    explanation: 'كلمة "اختبار" تُعرّف اختباراً جديداً.',
    difficulty: 'medium',
    category: 'الاختبارات',
    points: 2,
  },
  {
    id: 'a41',
    question: 'ما هي التأكيدات (Assertions)؟',
    options: ['التحقق من صحة نتائج الاختبار', 'إنشاء متغيرات', 'طباعة القيم', 'حذف الكود'],
    correctAnswer: 0,
    explanation: 'التأكيدات تتحقق من أن النتائج مطابقة للمتوقع.',
    difficulty: 'medium',
    category: 'الاختبارات',
    points: 2,
  },
  {
    id: 'a42',
    question: 'كيف تكتب تأكيد المساواة؟',
    options: ['تأكيد.يساوي(الفعلي، المتوقع)', 'assert.equal(actual, expected)', 'expect(actual).toBe(expected)', 'assertEquals(actual, expected)'],
    correctAnswer: 0,
    explanation: 'تأكيد.يساوي يتحقق من تساوي القيمتين.',
    difficulty: 'medium',
    category: 'الاختبارات',
    points: 2,
  },
  // === الأمان ===
  {
    id: 'a43',
    question: 'ما هو حقن SQL؟',
    options: ['إدخال كود ضار عبر المدخلات', 'تحسين الاستعلامات', 'تشفير البيانات', 'ضغط البيانات'],
    correctAnswer: 0,
    explanation: 'حقن SQL هجوم يُدخل كوداً ضاراً عبر مدخلات المستخدم.',
    difficulty: 'hard',
    category: 'الأمان',
    points: 3,
  },
  {
    id: 'a44',
    question: 'كيف تمنع حقن SQL؟',
    options: ['استخدام الاستعلامات المُعّدة', 'تجاهل المدخلات', 'قبول كل المدخلات', 'لا يمكن منعه'],
    correctAnswer: 0,
    explanation: 'الاستعلامات المُعّدة تمنع حقن SQL بفصل الكود عن البيانات.',
    difficulty: 'hard',
    category: 'الأمان',
    points: 3,
  },
  {
    id: 'a45',
    question: 'ما هو XSS؟',
    options: ['حقن سكريبت عبر المواقع', 'تحسين الأداء', 'تشفير البيانات', 'ضغط البيانات'],
    correctAnswer: 0,
    explanation: 'XSS هجوم يُدخل سكريبت ضار في صفحات الويب.',
    difficulty: 'hard',
    category: 'الأمان',
    points: 3,
  },
  {
    id: 'a46',
    question: 'كيف تمنع XSS؟',
    options: ['تشفير المخرجات', 'تجاهل المدخلات', 'قبول كل المدخلات', 'لا يمكن منعه'],
    correctAnswer: 0,
    explanation: 'تشفير المخرجات يمنع XSS بتحويل الأحرف الخاصة.',
    difficulty: 'hard',
    category: 'الأمان',
    points: 3,
  },
  // === المزيد ===
  {
    id: 'a47',
    question: 'ما هو Regular Expression؟',
    options: ['نمط للبحث والمطابقة في النصوص', 'دالة رياضية', 'متغير خاص', 'صفة للنص'],
    correctAnswer: 0,
    explanation: 'التعبيرات النمطية تُستخدم للبحث والمطابقة في النصوص.',
    difficulty: 'hard',
    category: 'النصوص',
    points: 3,
  },
  {
    id: 'a48',
    question: 'كيف تنشئ تعبيراً نمطياً؟',
    options: ['نمط("[0-9]+")', '/[0-9]+/', 'RegExp("[0-9]+")', 'regex("[0-9]+")'],
    correctAnswer: 0,
    explanation: 'كلمة "نمط" تُنشئ تعبيراً نمطياً جديداً.',
    difficulty: 'hard',
    category: 'النصوص',
    points: 3,
  },
  {
    id: 'a49',
    question: 'ما هي الـ Generics؟',
    options: ['أنواع عامة تعمل مع أي نوع', 'دوال عامة', 'متغيرات عامة', 'أصناف عامة'],
    correctAnswer: 0,
    explanation: 'الـ Generics تسمح بكتابة كود يعمل مع أنواع مختلفة.',
    difficulty: 'expert',
    category: 'الأنواع المتقدمة',
    points: 4,
  },
  {
    id: 'a50',
    question: 'كيف تُعرّف دالة عامة؟',
    options: ['دالة<ن> الاسم(المعامل: ن) { }', 'function name<T>(param: T) { }', 'def name[T](param: T):', 'func name<T>(param: T) {}'],
    correctAnswer: 0,
    explanation: 'الدوال العامة تُعرّف مع معامل نوع بين < >.',
    difficulty: 'expert',
    category: 'الأنواع المتقدمة',
    points: 4,
  },
  {
    id: 'a51',
    question: 'ما هي الـ Traits؟',
    options: ['تعريف سلوك مشترك بين الأصناف', 'خصائص الصنف', 'دوال الصنف', 'متغيرات الصنف'],
    correctAnswer: 0,
    explanation: 'الـ Traits تُعرّف سلوكاً مشتركاً يمكن تنفيذه في أصناف متعددة.',
    difficulty: 'expert',
    category: 'البرمجة الكائنية',
    points: 4,
  },
  {
    id: 'a52',
    question: 'ما هو Pattern Matching؟',
    options: ['مطابقة الأنماط للتعامل مع البيانات', 'البحث في النصوص', 'مطابقة الألوان', 'مطابقة الحروف'],
    correctAnswer: 0,
    explanation: 'مطابقة الأنماط تسمح بتفكيك البيانات والتعامل معها حسب شكلها.',
    difficulty: 'expert',
    category: 'الأنواع المتقدمة',
    points: 4,
  },
  {
    id: 'a53',
    question: 'كيف تستخدم مطابقة الأنماط؟',
    options: ['طابق القيمة { نمط1 => ... نمط2 => ... }', 'switch(value) { case pattern: ... }', 'match value { pattern => ... }', 'case value of pattern: ...'],
    correctAnswer: 0,
    explanation: 'كلمة "طابق" تُستخدم لمطابقة الأنماط.',
    difficulty: 'expert',
    category: 'الأنواع المتقدمة',
    points: 4,
  },
  {
    id: 'a54',
    question: 'ما هو الـ Macro؟',
    options: ['كود يُولّد كوداً آخر', 'دالة كبيرة', 'متغير كبير', 'صنف كبير'],
    correctAnswer: 0,
    explanation: 'الـ Macros تسمح بكتابة كود يُولّد كوداً آخر في وقت الترجمة.',
    difficulty: 'expert',
    category: 'الميتا برمجة',
    points: 4,
  },
  {
    id: 'a55',
    question: 'ما هي الميتا برمجة؟',
    options: ['برمجة تُعالج الكود كبيانات', 'برمجة كبيرة', 'برمجة متقدمة', 'برمجة ذكية'],
    correctAnswer: 0,
    explanation: 'الميتا برمجة تسمح للكود بفحص وتعديل نفسه أو كود آخر.',
    difficulty: 'expert',
    category: 'الميتا برمجة',
    points: 4,
  },
  {
    id: 'a56',
    question: 'ما هو FFI؟',
    options: ['واجهة لاستدعاء دوال من لغات أخرى', 'تنسيق ملفات', 'بروتوكول شبكة', 'نوع بيانات'],
    correctAnswer: 0,
    explanation: 'FFI (Foreign Function Interface) يسمح باستدعاء دوال من مكتبات C وغيرها.',
    difficulty: 'expert',
    category: 'التكامل',
    points: 4,
  },
  {
    id: 'a57',
    question: 'ما هي الـ SIMD؟',
    options: ['تعليمة واحدة لبيانات متعددة', 'سرعة عالية', 'ذاكرة كبيرة', 'معالجة متوازية'],
    correctAnswer: 0,
    explanation: 'SIMD تُنفّذ نفس التعليمة على عدة بيانات بالتوازي.',
    difficulty: 'expert',
    category: 'الأداء',
    points: 4,
  },
  {
    id: 'a58',
    question: 'ما هي عملية البروفايل (Profiling)؟',
    options: ['تحليل أداء البرنامج', 'تحسين الكود', 'تشفير البيانات', 'ضغط الملفات'],
    correctAnswer: 0,
    explanation: 'البروفايل يُحدّد أجزاء الكود التي تستهلك أكثر الموارد.',
    difficulty: 'hard',
    category: 'الأداء',
    points: 3,
  },
  {
    id: 'a59',
    question: 'كيف تُنفّذ البروفايل في لغة المرجع؟',
    options: ['بروفايل() أو --profile', 'profile()', '--debug', '--analyze'],
    correctAnswer: 0,
    explanation: 'أداة البروفايل تُظهر استهلاك الوقت والذاكرة.',
    difficulty: 'hard',
    category: 'الأداء',
    points: 3,
  },
  {
    id: 'a60',
    question: 'ما هو تعقيد الخوارزمية O(n log n)؟',
    options: ['خوارزمية تقسيم ثم معالجة', 'خوارزمية خطية', 'خوارزمية مربعة', 'خوارزمية ثابتة'],
    correctAnswer: 0,
    explanation: 'O(n log n) تظهر في خوارزميات الترتيب مثل الدمج والسريع.',
    difficulty: 'expert',
    category: 'الخوارزميات',
    points: 4,
  },
];

// ============================================
// أسئلة المستوى الخبير - Professional Questions (40+ سؤال)
// ============================================

export const professionalQuestions: Question[] = [
  // === JIT Compiler المتقدم ===
  {
    id: 'p1',
    question: 'ما هو Tier 0 في JIT Compiler؟',
    options: ['المفسر الأساسي (Interpreter Baseline)', 'التحسين الأول', 'SIMD Optimizations', 'Tracing JIT'],
    correctAnswer: 0,
    explanation: 'Tier 0 هو التنفيذ بالمفسر قبل أي تحسين JIT.',
    difficulty: 'expert',
    category: 'JIT Compiler',
    points: 4,
  },
  {
    id: 'p2',
    question: 'متى يُفعّل Tier 1 (Baseline JIT)؟',
    options: ['بعد 50 تنفيذ', 'فوراً', 'بعد 1000 تنفيذ', 'بعد 5 تنفيذات'],
    correctAnswer: 0,
    explanation: 'Baseline JIT يُفعّل بعد 50 تنفيذ لنفس الكود.',
    difficulty: 'expert',
    category: 'JIT Compiler',
    points: 4,
  },
  {
    id: 'p3',
    question: 'متى يُفعّل Tracing JIT (Tier 4)؟',
    options: ['بعد 5000 تنفيذ', 'بعد 100 تنفيذ', 'فوراً', 'بعد 50 تنفيذ'],
    correctAnswer: 0,
    explanation: 'Tracing JIT يُفعّل بعد 5000 تنفيذ للكود الساخن.',
    difficulty: 'expert',
    category: 'JIT Compiler',
    points: 4,
  },
  {
    id: 'p4',
    question: 'ما هي Inline Caching؟',
    options: ['تخزين نتائج استدعاءات الدوال', 'حذف الدوال', 'نسخ الدوال', 'تشفير الدوال'],
    correctAnswer: 0,
    explanation: 'Inline Caching تُسرّع استدعاءات الدوال بتخزين مواقعها.',
    difficulty: 'expert',
    category: 'JIT Compiler',
    points: 4,
  },
  {
    id: 'p5',
    question: 'ما هي Escape Analysis؟',
    options: ['تحليل إذا كان الكائن يهرب من الدالة', 'تحليل الأخطاء', 'تحليل الأداء', 'تحليل الذاكرة'],
    correctAnswer: 0,
    explanation: 'Escape Analysis تُحدد إذا كان الكائن يمكن تخصيصه على المكدس.',
    difficulty: 'expert',
    category: 'التحسين',
    points: 4,
  },
  // === الأداء ===
  {
    id: 'p6',
    question: 'ما هي عدد العمليات الحسابية في الثانية مع JIT؟',
    options: ['3.6M عملية/ثانية', '100K عملية/ثانية', '1M عملية/ثانية', '500K عملية/ثانية'],
    correctAnswer: 0,
    explanation: 'JIT يُتيح تنفيذ 3.6 مليون عملية حسابية في الثانية.',
    difficulty: 'expert',
    category: 'الأداء',
    points: 4,
  },
  {
    id: 'p7',
    question: 'كم عملية/ثانية في اختبار الضغط للغة المرجع؟',
    options: ['19.9M عملية/ثانية', '1M عملية/ثانية', '5M عملية/ثانية', '10M عملية/ثانية'],
    correctAnswer: 0,
    explanation: 'لغة المرجع تحقق 19.9 مليون عملية في الثانية في اختبار الضغط.',
    difficulty: 'expert',
    category: 'الأداء',
    points: 4,
  },
  // === النشر والإنتاج ===
  {
    id: 'p8',
    question: 'ما هو أول خطوة لنشر تطبيق لغة المرجع؟',
    options: ['بناء النسخة الإنتاجية', 'حذف الكود المصدري', 'نسخ الملفات', 'نشر مباشر'],
    correctAnswer: 0,
    explanation: 'البناء الإنتاجي يُحسّن الكود ويُجهّزه للنشر.',
    difficulty: 'hard',
    category: 'النشر',
    points: 3,
  },
  {
    id: 'p9',
    question: 'ما هي أفضل ممارسة للتعامل مع الأخطاء في الإنتاج؟',
    options: ['تسجيل الأخطاء ومراقبتها', 'تجاهل الأخطاء', 'إيقاف البرنامج', 'طباعة الأخطاء للمستخدم'],
    correctAnswer: 0,
    explanation: 'تسجيل ومراقبة الأخطاء يُتيح اكتشاف وحل المشاكل بسرعة.',
    difficulty: 'hard',
    category: 'النشر',
    points: 3,
  },
  {
    id: 'p10',
    question: 'ما هي الـ CI/CD؟',
    options: ['التكامل والنشر المستمر', 'التشفير المستمر', 'النسخ الاحتياطي', 'المراقبة'],
    correctAnswer: 0,
    explanation: 'CI/CD تُؤتمت اختبار ونشر التطبيق.',
    difficulty: 'hard',
    category: 'النشر',
    points: 3,
  },
  // === التكامل ===
  {
    id: 'p11',
    question: 'كيف تتكامل لغة المرجع مع أنظمة أخرى؟',
    options: ['عبر واجهات برمجة التطبيقات (APIs)', 'لا تتكامل', 'نسخ الملفات', 'إعادة كتابة الكود'],
    correctAnswer: 0,
    explanation: 'APIs تُتيح التكامل مع الأنظمة والخدمات الخارجية.',
    difficulty: 'hard',
    category: 'التكامل',
    points: 3,
  },
  {
    id: 'p12',
    question: 'ما هي ميزة FFI في لغة المرجع؟',
    options: ['استدعاء دوال من لغات أخرى', 'تشفير الكود', 'ضغط الملفات', 'تسريع الشبكة'],
    correctAnswer: 0,
    explanation: 'FFI (Foreign Function Interface) يُتيح استدعاء دوال من مكتبات C وغيرها.',
    difficulty: 'expert',
    category: 'التكامل',
    points: 4,
  },
  // === مكتبات مخصصة ===
  {
    id: 'p13',
    question: 'كيف تُنشئ مكتبة قابلة لإعادة الاستخدام؟',
    options: ['تغليف الدوال في وحدة مستقلة', 'كتابة كل شيء في ملف واحد', 'نسخ الكود لكل مشروع', 'استخدام لغة أخرى'],
    correctAnswer: 0,
    explanation: 'المكتبات تُبنى بتغليف الدوال والأصناف في وحدات مستقلة.',
    difficulty: 'hard',
    category: 'المكتبات',
    points: 3,
  },
  {
    id: 'p14',
    question: 'ما هو التوثيق الجيد للمكتبات؟',
    options: ['شرح كل دالة مع أمثلة', 'لا حاجة للتوثيق', 'توثيق جزئي', 'توثيق باللغة الإنجليزية فقط'],
    correctAnswer: 0,
    explanation: 'التوثيق الشامل مع الأمثلة يُسهّل استخدام المكتبة.',
    difficulty: 'hard',
    category: 'المكتبات',
    points: 3,
  },
  // === أمن ===
  {
    id: 'p15',
    question: 'ما هي أفضل ممارسة أمنية للمدخلات؟',
    options: ['التحقق والتنظيف قبل المعالجة', 'قبول كل المدخلات', 'رفض كل المدخلات', 'تخزين كما هي'],
    correctAnswer: 0,
    explanation: 'التحقق من المدخلات يحمي من الهجمات مثل XSS و SQL Injection.',
    difficulty: 'hard',
    category: 'الأمان',
    points: 3,
  },
  {
    id: 'p16',
    question: 'كيف تحمي كلمات المرور في التطبيق؟',
    options: ['تشفيرها بـ bcrypt أو مشابه', 'تخزينها كنص عادي', 'تشفير بسيط', 'حفظها في الكود'],
    correctAnswer: 0,
    explanation: 'bcrypt يُشفر كلمات المرور بشكل آمن مع salt.',
    difficulty: 'hard',
    category: 'الأمان',
    points: 3,
  },
  {
    id: 'p17',
    question: 'ما هو CSRF؟',
    options: ['تزوير طلب عبر المواقع', 'تشفير البيانات', 'ضغط البيانات', 'تحسين الأداء'],
    correctAnswer: 0,
    explanation: 'CSRF هجوم يُجبر المستخدم على تنفيذ إجراء غير مقصود.',
    difficulty: 'expert',
    category: 'الأمان',
    points: 4,
  },
  {
    id: 'p18',
    question: 'كيف تمنع CSRF؟',
    options: ['استخدام رموز CSRF', 'تجاهل الطلبات', 'قبول كل الطلبات', 'لا يمكن منعه'],
    correctAnswer: 0,
    explanation: 'رموز CSRF تتحقق من أن الطلب من المصدر الصحيح.',
    difficulty: 'expert',
    category: 'الأمان',
    points: 4,
  },
  // === اختبارات ===
  {
    id: 'p19',
    question: 'ما هو نوع الاختبار الذي يتحقق من وحدة واحدة من الكود؟',
    options: ['اختبار الوحدة (Unit Test)', 'اختبار التكامل', 'اختبار الأداء', 'اختبار الواجهة'],
    correctAnswer: 0,
    explanation: 'اختبار الوحدة يختبر دالة أو صنف بشكل معزول.',
    difficulty: 'medium',
    category: 'الاختبارات',
    points: 2,
  },
  {
    id: 'p20',
    question: 'ما هو اختبار التكامل؟',
    options: ['اختبار تفاعل الوحدات معاً', 'اختبار وحدة واحدة', 'اختبار الأداء', 'اختبار الواجهة'],
    correctAnswer: 0,
    explanation: 'اختبار التكامل يتحقق من عمل الوحدات معاً.',
    difficulty: 'medium',
    category: 'الاختبارات',
    points: 2,
  },
  {
    id: 'p21',
    question: 'ما هو TDD؟',
    options: ['التطوير المبني على الاختبارات', 'التطوير السريع', 'التطوير الأمني', 'التطوير الذكي'],
    correctAnswer: 0,
    explanation: 'TDD يكتب الاختبارات قبل الكود.',
    difficulty: 'hard',
    category: 'الاختبارات',
    points: 3,
  },
  {
    id: 'p22',
    question: 'ما هو Code Coverage؟',
    options: ['نسبة الكود المُغطى بالاختبارات', 'تغطية الكود بالتعليقات', 'تغطية الكود بالتوثيق', 'تغطية الكود بالأمان'],
    correctAnswer: 0,
    explanation: 'Code Coverage يُقيس نسبة الكود المُختبرة.',
    difficulty: 'hard',
    category: 'الاختبارات',
    points: 3,
  },
  // === تصميم البرمجيات ===
  {
    id: 'p23',
    question: 'ما هو مبدأ SOLID؟',
    options: ['مبادئ تصميم البرمجيات', 'لغة برمجة', 'إطار عمل', 'قاعدة بيانات'],
    correctAnswer: 0,
    explanation: 'SOLID هي 5 مبادئ لتصميم برمجيات قابلة للصيانة.',
    difficulty: 'hard',
    category: 'التصميم',
    points: 3,
  },
  {
    id: 'p24',
    question: 'ما هو مبدأ المسؤولية الواحدة؟',
    options: ['كل صنف له سبب واحد للتغيير', 'كل صنف له وظائف متعددة', 'الأصناف لا تتغير', 'التغيير ممنوع'],
    correctAnswer: 0,
    explanation: 'المسؤولية الواحدة تعني أن الصنف يقوم بشيء واحد فقط.',
    difficulty: 'hard',
    category: 'التصميم',
    points: 3,
  },
  {
    id: 'p25',
    question: 'ما هو Dependency Injection؟',
    options: ['تمرير التبعيات من الخارج', 'إنشاء التبعيات داخل الصنف', 'حذف التبعيات', 'تشفير التبعيات'],
    correctAnswer: 0,
    explanation: 'DI يجعل الكود أكثر مرونة وقابلاً للاختبار.',
    difficulty: 'expert',
    category: 'التصميم',
    points: 4,
  },
  // === قواعد البيانات ===
  {
    id: 'p26',
    question: 'ما هي قاعدة البيانات؟',
    options: ['نظام لتنظيم وتخزين البيانات', 'ملف نصي', 'جدول بسيط', 'قائمة'],
    correctAnswer: 0,
    explanation: 'قاعدة البيانات تُنظّم وتُخزّن البيانات بكفاءة.',
    difficulty: 'medium',
    category: 'قواعد البيانات',
    points: 2,
  },
  {
    id: 'p27',
    question: 'ما هي قاعدة البيانات العلائقية؟',
    options: ['قاعدة بيانات بجداول مرتبطة', 'قاعدة بيانات بالملفات', 'قاعدة بيانات نصية', 'قاعدة بيانات بسيطة'],
    correctAnswer: 0,
    explanation: 'قواعد البيانات العلائقية تستخدم جداول وعلاقات.',
    difficulty: 'medium',
    category: 'قواعد البيانات',
    points: 2,
  },
  {
    id: 'p28',
    question: 'ما هو الفهرس (Index) في قاعدة البيانات؟',
    options: ['هيكل يُسرّع البحث', 'ترتيب البيانات', 'حذف البيانات', 'نسخ البيانات'],
    correctAnswer: 0,
    explanation: 'الفهرس يُسرّع البحث في الجداول الكبيرة.',
    difficulty: 'hard',
    category: 'قواعد البيانات',
    points: 3,
  },
  {
    id: 'p29',
    question: 'ما هي المعاملة (Transaction)؟',
    options: ['مجموعة عمليات تنفذ كوحدة واحدة', 'عملية واحدة', 'استعلام بسيط', 'حذف بيانات'],
    correctAnswer: 0,
    explanation: 'المعاملة تضمن تنفيذ جميع العمليات أو لا شيء.',
    difficulty: 'hard',
    category: 'قواعد البيانات',
    points: 3,
  },
  {
    id: 'p30',
    question: 'ما هي خصائص ACID؟',
    options: ['الذرية، الاتساق، العزل، الديمومة', 'السرعة، الأمان، الحجم، التوفر', 'القراءة، الكتابة، الحذف، التحديث', 'لا توجد خصائص'],
    correctAnswer: 0,
    explanation: 'ACID تضمن موثوقية المعاملات في قواعد البيانات.',
    difficulty: 'expert',
    category: 'قواعد البيانات',
    points: 4,
  },
  // === البنية التحتية ===
  {
    id: 'p31',
    question: 'ما هو Docker؟',
    options: ['منصة للحاويات', 'لغة برمجة', 'قاعدة بيانات', 'نظام تشغيل'],
    correctAnswer: 0,
    explanation: 'Docker يُتيح تشغيل التطبيقات في حاويات معزولة.',
    difficulty: 'medium',
    category: 'البنية التحتية',
    points: 2,
  },
  {
    id: 'p32',
    question: 'ما هو Kubernetes؟',
    options: ['نظام لإدارة الحاويات', 'قاعدة بيانات', 'لغة برمجة', 'برنامج تشغيل'],
    correctAnswer: 0,
    explanation: 'Kubernetes يُدير وينسّق الحاويات على نطاق واسع.',
    difficulty: 'hard',
    category: 'البنية التحتية',
    points: 3,
  },
  {
    id: 'p33',
    question: 'ما هي الخدمات المصغرة (Microservices)؟',
    options: ['تقسيم التطبيق لخدمات صغيرة مستقلة', 'تطبيق واحد كبير', 'خدمة واحدة', 'لا يوجد تقسيم'],
    correctAnswer: 0,
    explanation: 'الخدمات المصغرة تقسم التطبيق لأجزاء مستقلة قابلة للتطوير.',
    difficulty: 'hard',
    category: 'البنية التحتية',
    points: 3,
  },
  {
    id: 'p34',
    question: 'ما هو Load Balancer؟',
    options: ['توزيع الحمل على خوادم متعددة', 'زيادة الحمل', 'تقليل الحمل', 'حذف الحمل'],
    correctAnswer: 0,
    explanation: 'Load Balancer يوزع الطلبات على خوادم متعددة.',
    difficulty: 'hard',
    category: 'البنية التحتية',
    points: 3,
  },
  {
    id: 'p35',
    question: 'ما هو Caching؟',
    options: ['تخزين مؤقت للبيانات المتكررة', 'حذف البيانات', 'تشفير البيانات', 'ضغط البيانات'],
    correctAnswer: 0,
    explanation: 'التخزين المؤقت يُسرّع الوصول للبيانات المتكررة.',
    difficulty: 'medium',
    category: 'الأداء',
    points: 2,
  },
  // === مراقبة ===
  {
    id: 'p36',
    question: 'ما هي مراقبة التطبيقات؟',
    options: ['تتبع أداء وسلوك التطبيق', 'التحكم بالمستخدمين', 'تشفير البيانات', 'حذف الأخطاء'],
    correctAnswer: 0,
    explanation: 'المراقبة تكتشف المشاكل وتُحسّن الأداء.',
    difficulty: 'medium',
    category: 'المراقبة',
    points: 2,
  },
  {
    id: 'p37',
    question: 'ما هي Logs؟',
    options: ['سجلات أحداث التطبيق', 'كود التطبيق', 'بيانات المستخدم', 'ملفات النظام'],
    correctAnswer: 0,
    explanation: 'السجلات تُسجل الأحداث والأخطاء للتحليل.',
    difficulty: 'medium',
    category: 'المراقبة',
    points: 2,
  },
  {
    id: 'p38',
    question: 'ما هو Alerting؟',
    options: ['إرسال تنبيهات عند المشاكل', 'إرسال رسائل عادية', 'حذف التنبيهات', 'تشفير التنبيهات'],
    correctAnswer: 0,
    explanation: 'التنبيهات تُخطر الفريق عند حدوث مشاكل.',
    difficulty: 'medium',
    category: 'المراقبة',
    points: 2,
  },
  // === إضافية ===
  {
    id: 'p39',
    question: 'ما هو API Gateway؟',
    options: ['بوابة موحدة للوصول للخدمات', 'بوابة أمنية', 'بوابة البيانات', 'بوابة الشبكة'],
    correctAnswer: 0,
    explanation: 'API Gateway يُوحد الدخول للخدمات المصغرة.',
    difficulty: 'hard',
    category: 'البنية التحتية',
    points: 3,
  },
  {
    id: 'p40',
    question: 'ما هو Service Mesh؟',
    options: ['طبقة للتواصل بين الخدمات', 'شبكة الخدمات', 'قاعدة بيانات', 'نظام تشغيل'],
    correctAnswer: 0,
    explanation: 'Service Mesh يُدير التواصل بين الخدمات المصغرة.',
    difficulty: 'expert',
    category: 'البنية التحتية',
    points: 4,
  },
];

// ============================================
// تجميع كل الأسئلة
// ============================================

export const allQuestions = {
  beginner: beginnerQuestions,
  intermediate: intermediateQuestions,
  advanced: advancedQuestions,
  professional: professionalQuestions,
};

// دالة للحصول على أسئلة عشوائية
export function getRandomQuestions(
  level: 'beginner' | 'intermediate' | 'advanced' | 'professional',
  count: number
): Question[] {
  const questions = allQuestions[level];
  const shuffled = [...questions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

// دالة لخلط الخيارات
export function shuffleOptions(question: Question): Question {
  const optionsWithIndex = question.options.map((opt, idx) => ({
    option: opt,
    isCorrect: idx === question.correctAnswer,
  }));

  const shuffled = optionsWithIndex.sort(() => Math.random() - 0.5);

  return {
    ...question,
    options: shuffled.map(item => item.option),
    correctAnswer: shuffled.findIndex(item => item.isCorrect),
  };
}

// دالة لتوليد اختبار عشوائي
export function generateExam(
  level: 'beginner' | 'intermediate' | 'advanced' | 'professional',
  questionCount: number
): Question[] {
  const questions = getRandomQuestions(level, questionCount);
  return questions.map(q => shuffleOptions(q));
}
